const s = require('/home/greg/Documents/CLAUDE_PROJECTS/script-high-level-modules/node_modules/snarkjs')
const fs = require('fs')
;(async () => {
  const curve = await s.curves.getCurveFromName('bls12381')
  await s.powersOfTau.newAccumulator(curve, 8, 'pot_0.ptau')
  await s.powersOfTau.contribute('pot_0.ptau', 'pot_1.ptau', 'c1', 'entropy for a demonstration, not a ceremony')
  await s.powersOfTau.preparePhase2('pot_1.ptau', 'pot_final.ptau')
  await s.zKey.newZKey('mul.r1cs', 'pot_final.ptau', 'mul_0.zkey')
  await s.zKey.contribute('mul_0.zkey', 'mul.zkey', 'c1', 'entropy for a demonstration, not a ceremony')
  const vk = await s.zKey.exportVerificationKey('mul.zkey')
  fs.writeFileSync('vk.json', JSON.stringify(vk, null, 1))
  const { proof, publicSignals } = await s.groth16.prove('mul.zkey', 'mul.wtns')
  fs.writeFileSync('proof.json', JSON.stringify(proof, null, 1))
  fs.writeFileSync('public.json', JSON.stringify(publicSignals, null, 1))
  const ok = await s.groth16.verify(vk, publicSignals, proof)
  console.log('\n  snarkjs verifies its own proof:', ok)
  console.log('  public signals:', JSON.stringify(publicSignals))
  console.log('  vk curve:', vk.curve, ' nPublic:', vk.nPublic, ' IC points:', vk.IC.length)
  await curve.terminate()
  process.exit(ok ? 0 : 1)
})().catch(e => { console.log('ERR', e.message); process.exit(1) })
