'use strict'

// The catalogue, generated from the registry. A module is only reusable if it
// can be found and read without opening its source: what it takes, what it
// gives back, and which of its inputs the SPENDER supplies — that last column
// being the one that decides how carefully you have to read the module before
// building on it.

const fs = require('fs')
const path = require('path')
const lib = require('../src')

function row (d) {
  if (d.factory) return `| \`${d.name}(…)\` | *built per key or width* | | | |`
  const io = (xs) => xs.length ? xs.map((x) => `\`${x.name}\``).join(' ') : '—'
  const w = d.witnessed.length ? d.witnessed.map((x) => `\`${x}\``).join(' ') : '—'
  return `| \`${d.name}\` | ${io(d.inputs)} | ${io(d.outputs)} | ${w} | ${d.cases} |`
}

const entries = lib.catalog()
const table = [
  '| module | inputs | outputs | supplied by the spender | cases |',
  '| --- | --- | --- | --- | ---: |',
  ...entries.map(row)
].join('\n')

const predicates = entries.filter((e) => e.isPredicate).map((e) => `\`${e.name}\``)

const doc = `# The catalogue

<!-- generated by tools/catalog.js — do not edit by hand -->

${table}

A module with **no outputs** is a predicate: it asserts and returns nothing, and
\`predicate(module, params, { owner })\` turns it straight into a locking script
and the unlocking script that spends it. Today that is ${predicates.join(', ')}, plus
\`rsa.verify(key)\` and \`ecdsa.verify(cases)\` from the factories.

A module **with** outputs is a component — \`ec.add\` returns a point, \`hmac.sha256\`
returns a MAC — and something above it still has to say what makes the coin move.

The **supplied by the spender** column is the one to read first. Those inputs are
witnesses: values the module verifies rather than computes, because checking is
cheaper than computing. Every one of them owes both soundness and canonicity, and
[witnesses.md](witnesses.md) is about what happens when only the first is
delivered.
`

const out = path.join(__dirname, '..', 'docs', 'catalog.md')
if (process.argv.includes('--check')) {
  const existing = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : ''
  if (existing !== doc) { console.log('catalog: docs/catalog.md is out of date — run `npm run catalog`'); process.exit(1) }
  console.log(`catalog: docs/catalog.md matches the registry (${entries.length} entries)`)
} else {
  fs.writeFileSync(out, doc)
  console.log(doc)
}
