'use strict'

// What every module costs, measured by emitting it. `--check` fails if the
// table in docs/cost.md no longer matches the code, so the documented numbers
// are derived rather than transcribed.

const fs = require('fs')
const path = require('path')
const { moduleSize } = require('../src/testkit')
const int = require('../src/modules/int')
const bytes = require('../src/modules/bytes')
const u32 = require('../src/modules/u32')
const sha256 = require('../src/modules/sha256')
const rsaMod = require('../src/modules/rsa')
const hmac = require('../src/modules/hmac')
const totp = require('../src/modules/totp')
const ec = require('../src/modules/ec')
const ecdsa = require('../src/modules/ecdsa')
const merkle = require('../src/modules/merkle')
const txmod = require('../src/modules/tx')
const crypto = require('crypto')
const mleaves = Array.from({ length: 8 }, (_, i) => crypto.createHash('sha256').update('leaf' + i).digest())
const mtree = merkle.tree(mleaves)

const key = rsaMod.fixtureKey()
const P256 = (1n << 256n) - 189n
const P2048 = (1n << 2048n) - 1557n

const ROWS = [
  ['int.modadd', int.modadd, { n: P2048 }, '2048-bit modulus'],
  ['int.modsub', int.modsub, { n: P2048 }, '2048-bit modulus'],
  ['int.modmul', int.modmul, { n: P2048 }, '2048-bit modulus'],
  ['int.modmul', int.modmul, { n: P256 }, '256-bit modulus'],
  ['int.modinv', int.modinv, { n: P256 }, '256-bit, witnessed'],
  ['int.modexp', int.modexp, { n: P2048, e: 65537n }, 'e = 65537, 2048-bit'],
  ['int.modexp', int.modexp, { n: P2048, e: 3n }, 'e = 3, 2048-bit'],
  ['bytes.reverse', bytes.reverse, { width: 32 }, 'a 32-byte digest'],
  ['bytes.beToNum', bytes.beToNum, { width: 32 }, 'a 32-byte digest'],
  ['u32.rotr', u32.rotr, { k: 7 }, 'one rotation'],
  ['u32.xor', u32.xor, {}, 'one XOR'],
  ['u32.add', u32.add, {}, 'one addition mod 2³²'],
  ['u32.ch', u32.ch, {}, 'SHA-2 choose'],
  ['u32.maj', u32.maj, {}, 'SHA-2 majority'],
  ['sha256.Sigma1', u32.Sigma1, {}, 'one mixing function'],
  ['rsa.verify', rsaMod.verifier(key), { n: key.n, e: key.e, emLen: key.emLen }, 'RSA-2048, PKCS#1 v1.5'],
  ['hmac.sha256', hmac.sha256, { keyLen: 32 }, 'a 32-byte key'],
  ['hmac.sha1', hmac.sha1, { keyLen: 20 }, 'a 20-byte key'],
  ['totp.verify', totp.verify, { keyLen: 20, digits: 6 }, 'RFC 6238, 6 digits'],
  ['merkle.verify', merkle.verify(mtree.root, { depth: 3, leaves: mleaves }), { depth: 3, root: mtree.root }, 'depth 3 (8 leaves)'],
  ['merkle.verify', merkle.verify(mtree.root, { depth: 32, leaves: mleaves }), { depth: 32, root: mtree.root }, 'depth 32 (4 billion leaves)'],
  ['tx.locktime', txmod.locktime, {}, 'OP_PUSH_TX + nLockTime'],
  ['ec.add', ec.add, {}, 'secp256k1, witnessed inverse'],
  ['ec.double', ec.double, {}, 'secp256k1, witnessed inverse'],
  ['ec.mulG', ec.mulG(256, [1n]), {}, 'k·G, 256-bit, base fixed'],
  ['ec.mul', ec.mul(256, [1n]), {}, 'k·P, 256-bit, both runtime'],
  ['ecdsa.verify', ecdsa.verifier([ecdsa.signCase('22'.repeat(32), 'x')]), {}, 'arbitrary message, secp256k1'],
  ['sha256.block', sha256.block, {}, 'one block, no OP_SHA256']
]

const measured = ROWS.map(([name, m, params, note]) => {
  const { bytes: b, ops } = moduleSize(m, params)
  return { name, note, bytes: b, ops }
})

const table = [
  '| module | configuration | Script bytes | opcodes |',
  '| --- | --- | ---: | ---: |',
  ...measured.map((r) => `| \`${r.name}\` | ${r.note} | ${r.bytes.toLocaleString()} | ${r.ops.toLocaleString()} |`)
].join('\n')

const NATIVE = 1                                   // OP_SHA256
const at = (n) => measured.find((r) => r.name === n).bytes
const rebuilt = at('sha256.block')
const rsaCost = at('rsa.verify')
const ecdsaCost = at('ecdsa.verify')
const FEE_SAT_PER_KB = 1                           // state the rate; the reader can change it

const body = `<!-- generated by tools/cost-report.js — do not edit by hand -->
${table}

## What to read out of this

**\`rsa.verify\` is ${rsaCost.toLocaleString()} bytes.** A signature scheme Bitcoin has no
opcode for, at a size nobody needs to think about — because every operation RSA
needs is one Script opcode at any width.

**\`sha256.block\` is ${rebuilt.toLocaleString()} bytes** for one block: **${Math.round(rebuilt / NATIVE).toLocaleString()}×** what
\`OP_SHA256\` costs for the same answer. Same technique, four orders of magnitude
apart. The difference is only whether the primitive you need is already an
opcode — and 32-bit modular addition is not, so every one of them pays for two
endianness conversions.

**\`ecdsa.verify\` is ${ecdsaCost.toLocaleString()} bytes**, the most expensive thing here
by an order of magnitude, and the one worth justifying before use. It buys
something nothing else here does: an oracle signs with the secp256k1 key it
already has, over any message at all. Rabin verification is a few hundred bytes
and buys the same authenticity — with a key the oracle must hold specifically
for this purpose. That is the trade, and it is an engineering choice rather than
a technical limit.

At ${FEE_SAT_PER_KB} sat/KB, that most expensive module is about
${Math.ceil(ecdsaCost / 1000 * FEE_SAT_PER_KB)} satoshis of fee. Size stopped being the
question at Genesis; what it costs, and whether a cheaper construction buys the
same thing, is the question that replaced it.
`

const out = path.join(__dirname, '..', 'docs', 'cost.md')
const check = process.argv.includes('--check')
const existing = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : ''
const doc = `# What the modules cost\n\n${body}`

if (check) {
  if (existing !== doc) {
    console.log('cost-report: docs/cost.md is out of date — run `npm run cost`')
    process.exit(1)
  }
  console.log(`cost-report: docs/cost.md matches the code (${measured.length} modules)`)
} else {
  fs.writeFileSync(out, doc)
  console.log(doc)
}
