'use strict'

// THE PAPER'S TABLES, GENERATED FROM results.json.
//
// A paper is a document with a long half-life and no `npm test`. This
// repository has already had numbers drift inside documents it could check;
// a PDF is the case where nothing checks. So every figure the paper quotes in a
// table comes from here, and `npm test` fails if results.json and the code
// disagree.
//
//     source ──► measurement ──► results.json ──► paper/tables.md ──► the paper
//
// Prose still has to be written by hand, and prose can still be wrong. What
// cannot silently happen is a table that describes a version of the code that
// no longer exists.

const fs = require('fs')
const path = require('path')

const r = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'results.json'), 'utf8'))
const OUT = path.join(__dirname, '..', 'paper', 'tables.md')
const n = (x) => x.toLocaleString('en-US')
const pct = (x) => (x * 100).toFixed(1) + '%'

const M = (k) => r.modules[k]

const doc = `# Tables

<!-- generated by tools/paper.js from results.json — do not edit by hand -->
<!-- commit ${r.commit || 'unknown'} · ${r.generated} -->

## Table 1 — the field tower, as Bitcoin Script

Every module below is proven against \`bsv.Script.Interpreter\` under relay
policy flags at the BLS12-381 prime.

Two columns, because a module has two honest sizes and neither is *the* size.

**Standalone** is the module alone: it pushes the 381-bit prime itself, 49
bytes, which a locking script has to do once however many operations follow.

**Marginal** is the same module with the prime already supplied as a stack
value. For the small modules that is much smaller — \`fp2.mul\` is ${n(M('fp2.mul').marginal)} rather
than ${n(M('fp2.mul').bytes)}, a difference larger than the module. For the large ones it is slightly
*larger*, and the reason is worth stating: a prime pushed by the module's own
prologue sits directly above its inputs, while one supplied beneath twenty-four
of them is deeper, and an \`OP_PICK\` past index 16 costs a byte more. Neither
column is a lower bound on the other; the depth of a constant is part of its
cost.

| module | operation | standalone | marginal | opcodes |
| --- | --- | ---: | ---: | ---: |
| \`fp2.mul\` | Karatsuba, three Fp multiplications | ${n(M('fp2.mul').bytes)} | ${n(M('fp2.mul').marginal)} | ${n(M('fp2.mul').opcodes)} |
| \`fp2.sqr\` | two Fp multiplications | ${n(M('fp2.sqr').bytes)} | ${n(M('fp2.sqr').marginal)} | ${n(M('fp2.sqr').opcodes)} |
| \`fp2.add\` | | ${n(M('fp2.add').bytes)} | ${n(M('fp2.add').marginal)} | ${n(M('fp2.add').opcodes)} |
| \`fp2.sub\` | | ${n(M('fp2.sub').bytes)} | ${n(M('fp2.sub').marginal)} | ${n(M('fp2.sub').opcodes)} |
| \`fp2.neg\` | | ${n(M('fp2.neg').bytes)} | ${n(M('fp2.neg').marginal)} | ${n(M('fp2.neg').opcodes)} |
| \`fp2.conj\` | the Fp2 Frobenius, p ≡ 3 (mod 4) | ${n(M('fp2.conj').bytes)} | ${n(M('fp2.conj').marginal)} | ${n(M('fp2.conj').opcodes)} |
| \`fp2.mulXi\` | multiply by ξ = u + 1, no multiplications | ${n(M('fp2.mulXi').bytes)} | ${n(M('fp2.mulXi').marginal)} | ${n(M('fp2.mulXi').opcodes)} |
| \`fp2.inv\` | **witnessed**: a·a⁻¹ = 1, both bounds | ${n(M('fp2.inv').bytes)} | ${n(M('fp2.inv').marginal)} | ${n(M('fp2.inv').opcodes)} |
| \`fp6.mul\` | Karatsuba, six Fp2 multiplications | ${n(M('fp6.mul').bytes)} | ${n(M('fp6.mul').marginal)} | ${n(M('fp6.mul').opcodes)} |
| \`fp12.mul\` | Karatsuba, eighteen Fp2 multiplications | ${n(M('fp12.mul').bytes)} | ${n(M('fp12.mul').marginal)} | ${n(M('fp12.mul').opcodes)} |
| \`fp12.sqr\` | general squaring | ${n(M('fp12.sqr').bytes)} | ${n(M('fp12.sqr').marginal)} | ${n(M('fp12.sqr').opcodes)} |
| \`fp12.cycSqr\` | Granger–Scott, cyclotomic subgroup only | ${n(M('fp12.cycSqr').bytes)} | ${n(M('fp12.cycSqr').marginal)} | ${n(M('fp12.cycSqr').opcodes)} |
| \`fp12.mulLine\` | sparse: nine of twelve coefficients are zero | ${n(M('fp12.mulLine').bytes)} | ${n(M('fp12.mulLine').marginal)} | ${n(M('fp12.mulLine').opcodes)} |
| \`fp12.frob\` | f ↦ f^p, six conjugations and seven products | ${n(M('fp12.frob').bytes)} | ${n(M('fp12.frob').marginal)} | ${n(M('fp12.frob').opcodes)} |
| \`fp12.inv\` | **witnessed**: one Fp12 product and twelve bounds | ${n(M('fp12.inv').bytes)} | ${n(M('fp12.inv').marginal)} | ${n(M('fp12.inv').opcodes)} |
| \`fp12.powX\` | f ↦ f^\\|x\\|, MSB-first, 63 squarings and 5 products | ${n(M('fp12.powX').bytes)} | ${n(M('fp12.powX').marginal)} | ${n(M('fp12.powX').opcodes)} |
| \`g2.stepDouble\` | tangent at T, and 2T | ${n(M('g2.stepDouble').bytes)} | ${n(M('g2.stepDouble').marginal)} | ${n(M('g2.stepDouble').opcodes)} |
| \`g2.stepAdd\` | chord through T and Q, and T + Q | ${n(M('g2.stepAdd').bytes)} | ${n(M('g2.stepAdd').marginal)} | ${n(M('g2.stepAdd').opcodes)} |

**Cyclotomic squaring is ${pct(1 - M('fp12.cycSqr').marginal / M('fp12.sqr').marginal)} smaller than general squaring**, and the sparse line
product is ${pct(1 - M('fp12.mulLine').marginal / M('fp12.mul').marginal)} smaller than a general Fp12 product.

## Table 2 — the pairing

| stage | composition | bytes | opcodes | witnessed values |
| --- | --- | ---: | ---: | ---: |
| Miller loop | ${r.pairing.miller.tangents} tangents, ${r.pairing.miller.chords} chords, ${r.pairing.miller.lines} line products, ${r.pairing.miller.squarings} squarings | ${n(r.pairing.miller.bytes)} | ${n(r.pairing.miller.opcodes)} | ${n(r.pairing.miller.witnesses)} |
| final exponentiation | easy part, ${r.pairing.finalExp.ladders} ladders, ${r.pairing.finalExp.terms} terms, ${r.pairing.finalExp.frobenius} Frobenius maps | ${n(r.pairing.finalExp.bytes)} | ${n(r.pairing.finalExp.opcodes)} | ${n(r.pairing.finalExp.witnesses)} |
| **e(P, Q)** | the two, chained | **${n(r.pairing.e.bytes)}** | **${n(r.pairing.e.opcodes)}** | **${n(r.pairing.e.witnesses)}** |

The stages do not sum to the whole: chaining them costs
${n(r.pairing.e.bytes - r.pairing.miller.bytes - r.pairing.finalExp.bytes)} bytes that neither separate measurement contains.

## Table 3 — products of pairings share the accumulator

The squaring belongs to the *bit*, not to the line, so k pairings on one Miller
accumulator pay for ${r.pairing.miller.squarings} squarings between them and one final exponentiation.

| pairings | as a product | as separate pairings | saved |
| ---: | ---: | ---: | ---: |
${r.pairing.products.map((p) => `| ${p.pairs} | ${n(p.bytes)} | ${n(p.separately)} | ${p.saved === 0 ? '—' : n(p.saved)} |`).join('\n')}

Each pairing after the first costs about ${n(r.pairing.products[2].bytes - r.pairing.products[1].bytes)} bytes rather than ${n(r.pairing.e.bytes)}.

## Table 4 — a Groth16 verifier

e(A, B) · e(−L, γ) · e(−C, δ) = e(α, β), with ${r.pairing.groth16.publicInputs} public inputs fixed at lock time.

| | |
| --- | ---: |
| locking script | ${n(r.pairing.groth16.bytes)} bytes |
| opcodes | ${n(r.pairing.groth16.opcodes)} |
| witnessed values | ${n(r.pairing.groth16.witnesses)} |
| chosen by the spender | ${r.pairing.groth16.spenderChooses.join(', ')} |
| chosen by the locking script | γ, δ, L, and e(α, β) |

The second-to-last row is the soundness property. A spender who could choose γ
could choose one satisfying the equation for a proof of nothing.

## Table 5 — what the network has executed

| | bytes | share of a pairing | status |
| --- | ---: | ---: | --- |
| Miller loop, complete | ${n(r.pairing.miller.bytes)} | ${pct(r.pairing.onchain.millerShare)} | **mainnet** |
| final exponentiation, whole | ${n(r.pairing.finalExp.bytes)} | ${pct(r.pairing.finalExp.bytes / r.pairing.e.bytes)} | ${r.pairing.onchain.finalExpDeployable ? 'under policy, not deployed' : 'interpreter'} |
| e(P, Q), whole | ${n(r.pairing.e.bytes)} | 100% | interpreter |
| \`fp12.powX\`, superseded | ${n(r.pairing.onchain.supersededOnChain.bytes)} | — | mainnet |

**${pct(r.pairing.onchain.pairingShareOnChain)} of one pairing, by bytes, has been executed by the Bitcoin network**,
and it is the Miller-loop stage, complete.

The last row needs its caveat. \`fp12.powX\` — one f^|x| ladder, uncompressed —
was deployed and spent, and it is correct. It is no longer what the
implementation does: \`fp12.powXc\` replaced it at ${n(r.pairing.onchain.supersededOnChain.replacementBytes)} bytes, and the
final exponentiation calls that. Counting its bytes toward "a pairing on chain"
would be counting a version that no longer exists, so the figure above does not.

The default script-size policy is ${n(r.scriptPolicyBytes)} bytes. Compressed squaring brought
the final exponentiation to ${n(r.pairing.finalExp.bytes)}, **under that boundary**, so both stages
of a pairing are now individually relayable; only the whole pairing in one
script (${n(r.pairing.e.bytes)}) is not.

## Table 6 — field operations per pairing

Counted by running a pairing that agrees with an independent implementation on
all twelve Fp12 coefficients. Fp2 counts include the operations the Fp12
routines perform.

| | Fp2 mul | Fp2 sqr | Fp2 add | Fp2 sub | Fp2 inv | Fp12 mul | Fp12 sqr | Fp12 cycSqr | Fp12 line |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| Miller loop | ${n(r.operations.miller.fp2.mul)} | ${n(r.operations.miller.fp2.sqr)} | ${n(r.operations.miller.fp2.add)} | ${n(r.operations.miller.fp2.sub)} | ${n(r.operations.miller.fp2.inv)} | ${n(r.operations.miller.fp12.mul)} | ${n(r.operations.miller.fp12.sqr)} | ${n(r.operations.miller.fp12.cycSqr)} | ${n(r.operations.miller.fp12.mulLine)} |
| final exponentiation | ${n(r.operations.finalExp.fp2.mul)} | ${n(r.operations.finalExp.fp2.sqr)} | ${n(r.operations.finalExp.fp2.add)} | ${n(r.operations.finalExp.fp2.sub)} | ${n(r.operations.finalExp.fp2.inv)} | ${n(r.operations.finalExp.fp12.mul)} | ${n(r.operations.finalExp.fp12.sqr)} | ${n(r.operations.finalExp.fp12.cycSqr)} | ${n(r.operations.finalExp.fp12.mulLine)} |

## Table 7 — mainnet deployments

${r.deployments.length} deployments, each rebuilt byte for byte from the source and compared against
the chain by \`npm run verify:chain\`.

| module | locking script | deploy |
| --- | ---: | --- |
${r.deployments.map((d) => `| \`${d.name}\` | ${d.lockBytes ? n(d.lockBytes) : '—'} | \`${(d.deploy || '').slice(0, 16)}…\` |`).join('\n')}
`

// ── the prose, too ──────────────────────────────────────────────────────────
//
// Tables are generated, so they cannot drift. Prose is written by hand and can,
// and the first draft of paper.md already quoted 2,375 bytes for fp12.sqr, a
// figure that had been 2,301 since the modulus stopped being pushed per module.
//
// So the load-bearing figures are listed here and checked to be present,
// formatted exactly as they should appear. This does not verify that the
// sentence around a number is true — nothing can — but it does mean the paper
// cannot silently claim a size the implementation no longer has.
const PROSE = {
  'one pairing, bytes': n(r.pairing.e.bytes),
  'final exponentiation, bytes': n(r.pairing.finalExp.bytes),
  'Groth16 verifier, bytes': n(r.pairing.groth16.bytes),
  'Groth16 verifier, opcodes': n(r.pairing.groth16.opcodes),
  'script policy': n(r.scriptPolicyBytes),
  'saving on two pairings': n(r.pairing.products[1].saved),
  'saving on three pairings': n(r.pairing.products[2].saved),
  'share of a pairing on chain': pct(r.pairing.onchain.pairingShareOnChain),
  'final exponentiation as a share': pct(r.pairing.finalExp.bytes / r.pairing.e.bytes),
  'fp12.mul, marginal': n(M('fp12.mul').marginal),
  'fp12.sqr, marginal': n(M('fp12.sqr').marginal),
  'Miller loop witnesses': String(r.pairing.miller.witnesses),
  'deployments': String(r.deployments.length),
  'ladders in the final exponentiation': String(r.pairing.finalExp.ladders)
}

function checkProse () {
  const file = path.join(__dirname, '..', 'paper', 'paper.md')
  if (!fs.existsSync(file)) return []
  const text = fs.readFileSync(file, 'utf8')
  return Object.entries(PROSE).filter(([, value]) => !text.includes(value)).map(([what, value]) => `${what} (${value})`)
}

const check = process.argv.includes('--check')
const existing = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : ''
if (check) {
  if (existing !== doc) { console.log('paper: paper/tables.md is out of date — run `npm run paper`'); process.exit(1) }
  const missing = checkProse()
  if (missing.length) {
    console.log('paper: paper.md no longer quotes these measured figures —')
    for (const m of missing) console.log(`  ${m}`)
    process.exit(1)
  }
  console.log(`paper: tables.md matches results.json, and paper.md quotes all ${Object.keys(PROSE).length} load-bearing figures`)
} else {
  fs.writeFileSync(OUT, doc)
  const missing = checkProse()
  console.log(`paper: wrote paper/tables.md — 7 tables from results.json`)
  if (missing.length) {
    console.log('  paper.md does not quote:')
    for (const m of missing) console.log(`    ${m}`)
  }
}
