'use strict'

// THE PAPER'S TABLES, GENERATED FROM results.json.
//
// A paper is a document with a long half-life and no `npm test`. This
// repository has already had numbers drift inside documents it could check;
// a PDF is the case where nothing checks. So every figure the paper quotes in a
// table comes from here, and `npm test` fails if results.json and the code
// disagree.
//
//     source ──► measurement ──► results.json ──► paper/tables.md ──► the paper
//
// Prose still has to be written by hand, and prose can still be wrong. What
// cannot silently happen is a table that describes a version of the code that
// no longer exists.

const fs = require('fs')
const path = require('path')

const r = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'results.json'), 'utf8'))
const OUT = path.join(__dirname, '..', 'paper', 'tables.md')
const n = (x) => x.toLocaleString('en-US')
const pct = (x) => (x * 100).toFixed(1) + '%'

const M = (k) => r.modules[k]
const G8 = r.pairing.onchain.grothVerifierInOneTransaction

const doc = `# Tables

<!-- generated by tools/paper.js from results.json — do not edit by hand -->
<!-- commit ${r.commit || 'unknown'} · ${r.generated} -->

## Table 1 — the field tower, as Bitcoin Script

Every module below is proven against \`bsv.Script.Interpreter\` under relay
policy flags at the BLS12-381 prime.

Two columns, because a module has two honest sizes and neither is *the* size.

**Standalone** is the module alone: it pushes the 381-bit prime itself, 49
bytes, which a locking script has to do once however many operations follow.

**Marginal** is the same module with the prime already supplied as a stack
value. For the small modules that is much smaller — \`fp2.mul\` is ${n(M('fp2.mul').marginal)} rather
than ${n(M('fp2.mul').bytes)}, a difference larger than the module. For the large ones it is slightly
*larger*, and the reason is worth stating: a prime pushed by the module's own
prologue sits directly above its inputs, while one supplied beneath twenty-four
of them is deeper, and an \`OP_PICK\` past index 16 costs a byte more. Neither
column is a lower bound on the other; the depth of a constant is part of its
cost.

| module | operation | standalone | marginal | opcodes |
| --- | --- | ---: | ---: | ---: |
| \`fp2.mul\` | Karatsuba, three Fp multiplications | ${n(M('fp2.mul').bytes)} | ${n(M('fp2.mul').marginal)} | ${n(M('fp2.mul').opcodes)} |
| \`fp2.sqr\` | two Fp multiplications | ${n(M('fp2.sqr').bytes)} | ${n(M('fp2.sqr').marginal)} | ${n(M('fp2.sqr').opcodes)} |
| \`fp2.add\` | | ${n(M('fp2.add').bytes)} | ${n(M('fp2.add').marginal)} | ${n(M('fp2.add').opcodes)} |
| \`fp2.sub\` | | ${n(M('fp2.sub').bytes)} | ${n(M('fp2.sub').marginal)} | ${n(M('fp2.sub').opcodes)} |
| \`fp2.neg\` | | ${n(M('fp2.neg').bytes)} | ${n(M('fp2.neg').marginal)} | ${n(M('fp2.neg').opcodes)} |
| \`fp2.conj\` | the Fp2 Frobenius, p ≡ 3 (mod 4) | ${n(M('fp2.conj').bytes)} | ${n(M('fp2.conj').marginal)} | ${n(M('fp2.conj').opcodes)} |
| \`fp2.mulXi\` | multiply by ξ = u + 1, no multiplications | ${n(M('fp2.mulXi').bytes)} | ${n(M('fp2.mulXi').marginal)} | ${n(M('fp2.mulXi').opcodes)} |
| \`fp2.inv\` | **witnessed**: a·a⁻¹ = 1, both bounds | ${n(M('fp2.inv').bytes)} | ${n(M('fp2.inv').marginal)} | ${n(M('fp2.inv').opcodes)} |
| \`fp6.mul\` | Karatsuba, six Fp2 multiplications | ${n(M('fp6.mul').bytes)} | ${n(M('fp6.mul').marginal)} | ${n(M('fp6.mul').opcodes)} |
| \`fp12.mul\` | Karatsuba, eighteen Fp2 multiplications | ${n(M('fp12.mul').bytes)} | ${n(M('fp12.mul').marginal)} | ${n(M('fp12.mul').opcodes)} |
| \`fp12.sqr\` | general squaring | ${n(M('fp12.sqr').bytes)} | ${n(M('fp12.sqr').marginal)} | ${n(M('fp12.sqr').opcodes)} |
| \`fp12.cycSqr\` | Granger–Scott, cyclotomic subgroup only | ${n(M('fp12.cycSqr').bytes)} | ${n(M('fp12.cycSqr').marginal)} | ${n(M('fp12.cycSqr').opcodes)} |
| \`fp12.mulLine\` | sparse: nine of twelve coefficients are zero | ${n(M('fp12.mulLine').bytes)} | ${n(M('fp12.mulLine').marginal)} | ${n(M('fp12.mulLine').opcodes)} |
| \`fp12.frob\` | f ↦ f^p, six conjugations and seven products | ${n(M('fp12.frob').bytes)} | ${n(M('fp12.frob').marginal)} | ${n(M('fp12.frob').opcodes)} |
| \`fp12.inv\` | **witnessed**: one Fp12 product and twelve bounds | ${n(M('fp12.inv').bytes)} | ${n(M('fp12.inv').marginal)} | ${n(M('fp12.inv').opcodes)} |
| \`fp12.powX\` | f ↦ f^\\|x\\|, MSB-first, 63 squarings and 5 products | ${n(M('fp12.powX').bytes)} | ${n(M('fp12.powX').marginal)} | ${n(M('fp12.powX').opcodes)} |
| \`g2.stepDouble\` | tangent at T, and 2T | ${n(M('g2.stepDouble').bytes)} | ${n(M('g2.stepDouble').marginal)} | ${n(M('g2.stepDouble').opcodes)} |
| \`g2.stepAdd\` | chord through T and Q, and T + Q | ${n(M('g2.stepAdd').bytes)} | ${n(M('g2.stepAdd').marginal)} | ${n(M('g2.stepAdd').opcodes)} |
| \`g1.onCurve\` | y² = x³ + 4 | ${n(M('g1.onCurve').bytes)} | ${n(M('g1.onCurve').marginal)} | ${n(M('g1.onCurve').opcodes)} |
| \`g2.onCurve\` | y² = x³ + 4(u + 1) | ${n(M('g2.onCurve').bytes)} | ${n(M('g2.onCurve').marginal)} | ${n(M('g2.onCurve').opcodes)} |
| \`g1.inSubgroup\` | **witnessed**: the curve, and φ(P) = [−x²]P by two ladders | ${n(M('g1.inSubgroup').bytes)} | ${n(M('g1.inSubgroup').marginal)} | ${n(M('g1.inSubgroup').opcodes)} |
| \`g2.inSubgroup\` | the twist, and T = −ψ(Q) for the loop's T = [\\|x\\|]Q | ${n(M('g2.inSubgroup').bytes)} | ${n(M('g2.inSubgroup').marginal)} | ${n(M('g2.inSubgroup').opcodes)} |

**Cyclotomic squaring is ${pct(1 - M('fp12.cycSqr').marginal / M('fp12.sqr').marginal)} smaller than general squaring**, and the sparse line
product is ${pct(1 - M('fp12.mulLine').marginal / M('fp12.mul').marginal)} smaller than a general Fp12 product.

## Table 2 — the pairing

| stage | composition | bytes | opcodes | witnessed values |
| --- | --- | ---: | ---: | ---: |
| Miller loop | ${r.pairing.miller.tangents} tangents, ${r.pairing.miller.chords} chords, ${r.pairing.miller.lines} line products, ${r.pairing.miller.squarings} squarings | ${n(r.pairing.miller.bytes)} | ${n(r.pairing.miller.opcodes)} | ${n(r.pairing.miller.witnesses)} |
| final exponentiation | easy part, ${r.pairing.finalExp.ladders} ladders, ${r.pairing.finalExp.terms} terms, ${r.pairing.finalExp.frobenius} Frobenius maps | ${n(r.pairing.finalExp.bytes)} | ${n(r.pairing.finalExp.opcodes)} | ${n(r.pairing.finalExp.witnesses)} |
| **e(P, Q)** | the two, chained | **${n(r.pairing.e.bytes)}** | **${n(r.pairing.e.opcodes)}** | **${n(r.pairing.e.witnesses)}** |

The stages do not sum to the whole: chaining them costs
${n(r.pairing.e.bytes - r.pairing.miller.bytes - r.pairing.finalExp.bytes)} bytes that neither separate measurement contains.

## Table 3 — products of pairings share the accumulator

The squaring belongs to the *bit*, not to the line, so k pairings on one Miller
accumulator pay for ${r.pairing.miller.squarings} squarings between them and one final exponentiation.

| pairings | as a product | as separate pairings | saved |
| ---: | ---: | ---: | ---: |
${r.pairing.products.map((p) => `| ${p.pairs} | ${n(p.bytes)} | ${n(p.separately)} | ${p.saved === 0 ? '—' : n(p.saved)} |`).join('\n')}

Each pairing after the first costs about ${n(r.pairing.products[2].bytes - r.pairing.products[1].bytes)} bytes rather than ${n(r.pairing.e.bytes)}.

## Table 4 — a Groth16 verifier

e(A, B) · e(−L, γ) · e(−C, δ) = e(α, β), with ${r.pairing.groth16.publicInputs} public inputs fixed at lock time.

| | |
| --- | ---: |
| locking script | ${n(r.pairing.groth16.bytes)} bytes |
| opcodes | ${n(r.pairing.groth16.opcodes)} |
| witnessed values | ${n(r.pairing.groth16.witnesses)} |
| chosen by the spender | ${r.pairing.groth16.spenderChooses.join(', ')} |
| chosen by the locking script | γ, δ, L, and e(α, β) |
| subgroup checks, A, C ∈ G1 and B ∈ G2 | ${n(r.pairing.groth16.subgroupCheckBytes)} bytes, ${pct(r.pairing.groth16.subgroupCheckBytes / r.pairing.groth16.bytes)} |
| the same verifier without them | ${n(r.pairing.groth16.withoutSubgroupChecks)} bytes |

The row naming what the locking script chooses is the soundness property. A
spender who could choose γ could choose one satisfying the equation for a proof
of nothing. The subgroup rows are the other half of it: a point outside its
subgroup is still a point, and the pairing is not bilinear on it.

## Table 5 — what the network has executed

| | bytes | share of a pairing | status |
| --- | ---: | ---: | --- |
| Miller loop, complete | ${n(r.pairing.miller.bytes)} | ${pct(r.pairing.onchain.millerShare)} | **mainnet** |
| final exponentiation, complete | ${n(r.pairing.finalExp.bytes)} | ${pct(r.pairing.onchain.finalExpShare)} | **mainnet** |
| e(P, Q) in one script | ${n(r.pairing.e.bytes)} | 100% | interpreter |
| \`fp12.powX\`, superseded | ${n(r.pairing.onchain.supersededOnChain.bytes)} | — | mainnet |

**A complete BLS12-381 pairing has been evaluated by the Bitcoin network**, as
two inputs of one transaction:

| | |
| --- | --- |
| funding | \`${r.pairing.onchain.wholePairingInOneTransaction.deploy}\` |
| spend | \`${r.pairing.onchain.wholePairingInOneTransaction.spend}\` |
| input 0 | \`pairing.publish\`, ${n(r.pairing.onchain.wholePairingInOneTransaction.publishBytes)} bytes |
| input 1 | \`pairing.consume\`, ${n(r.pairing.onchain.wholePairingInOneTransaction.consumeBytes)} bytes |
| the spend | ${n(r.pairing.onchain.wholePairingInOneTransaction.spendBytes)} bytes, one OP_RETURN output |

The network verified that the Miller loop ran correctly on P and Q, that its
twelve outputs were published, that the same twelve were consumed, and that
their final exponentiation is e(P, Q).

What has **not** run on chain is a pairing in ONE SCRIPT. That is ${n(r.pairing.e.bytes)} bytes
against a ${n(r.scriptPolicyBytes)}-byte policy, and the ${n(r.pairing.onchain.chainingBytesNotOnChain)} bytes by which the whole
exceeds its two stages are the plumbing the transaction replaced.

The last row carries its own caveat. \`fp12.powX\` — one f^|x| ladder,
uncompressed — was deployed and spent and is correct, and it is no longer what
the implementation does: \`fp12.powXc\` replaced it at ${n(r.pairing.onchain.supersededOnChain.replacementBytes)} bytes. Counting
its bytes toward a pairing on chain would be counting a version that no longer
exists, so the figure above does not.

Compressed squaring is what made the second row possible: the final
exponentiation was ${n(592008)} bytes before it and is ${n(r.pairing.finalExp.bytes)} after, which is the
difference between over the policy boundary and under it.

## Table 6 — field operations per pairing

Counted by running a pairing that agrees with an independent implementation on
all twelve Fp12 coefficients. Fp2 counts include the operations the Fp12
routines perform.

| | Fp2 mul | Fp2 sqr | Fp2 add | Fp2 sub | Fp2 inv | Fp12 mul | Fp12 sqr | Fp12 cycSqr | Fp12 line |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| Miller loop | ${n(r.operations.miller.fp2.mul)} | ${n(r.operations.miller.fp2.sqr)} | ${n(r.operations.miller.fp2.add)} | ${n(r.operations.miller.fp2.sub)} | ${n(r.operations.miller.fp2.inv)} | ${n(r.operations.miller.fp12.mul)} | ${n(r.operations.miller.fp12.sqr)} | ${n(r.operations.miller.fp12.cycSqr)} | ${n(r.operations.miller.fp12.mulLine)} |
| final exponentiation | ${n(r.operations.finalExp.fp2.mul)} | ${n(r.operations.finalExp.fp2.sqr)} | ${n(r.operations.finalExp.fp2.add)} | ${n(r.operations.finalExp.fp2.sub)} | ${n(r.operations.finalExp.fp2.inv)} | ${n(r.operations.finalExp.fp12.mul)} | ${n(r.operations.finalExp.fp12.sqr)} | ${n(r.operations.finalExp.fp12.cycSqr)} | ${n(r.operations.finalExp.fp12.mulLine)} |

## Table 7 — mainnet deployments

${r.deployments.length} deployments, each rebuilt byte for byte from the source and compared against
the chain by \`npm run verify:chain\`. The count is generated from the ledger, so
this table and the prose cannot disagree about how many there are.

| module | locking script | deploy |
| --- | ---: | --- |
${r.deployments.map((d) => `| \`${d.name}\` | ${d.lockBytes ? n(d.lockBytes) : '—'} | \`${(d.deploy || '').slice(0, 16)}…\` |`).join('\n')}

**${r.deployments.length} of ${r.deployments.length} reconstruct exactly.**

## Table 8 — a Groth16 verifier across three inputs of one transaction

The three-pairing Miller loop alone is ${n(G8.millerLoopThreePairs)} bytes, past the policy, so
the loop itself is cut, at round ${G8.cutRound} of 63. Built by \`src/groth16spend.js\` and every
input verified before these figures were taken.

| input | computes | locking | unlocking | of which subgroup checks |
| --- | --- | ---: | ---: | ---: |
| 0 | A, C ∈ G1; rounds 1–${G8.cutRound} | ${n(G8.lockBytes[0])} | ${n(G8.unlockBytes[0])} | ${n(G8.subgroupBytes[0])} |
| 1 | rounds ${G8.cutRound + 1}–63; B ∈ G2 | ${n(G8.lockBytes[1])} | ${n(G8.unlockBytes[1])} | ${n(G8.subgroupBytes[1])} |
| 2 | final exponentiation against e(α, β) | ${n(G8.lockBytes[2])} | ${n(G8.unlockBytes[2])} | — |
| output | the blob, ${G8.blobValues} field elements | ${n(G8.blobBytes)} | — | — |

The transaction is ${n(G8.txBytes)} bytes. Its three OP_PUSH_TX preimages were ground
together over nLockTime, ${n(G8.grindTries)} tries for a triple. Every stage binds its
siblings through hashPrevouts, ${G8.siblingBytes} bytes apiece.

${G8.deployed
  ? `**On mainnet**: funding \`${G8.deployed.deploy}\`, spend \`${G8.deployed.spend}\`. How the spend reached a block — refused by the relay path for its validation time, and taken directly by the pool that mined it — is §8.3.`
  : 'Verified against the interpreter under relay policy flags. **Not yet funded on chain.**'}
`

// ── the prose, too ──────────────────────────────────────────────────────────
//
// Tables are generated, so they cannot drift. Prose is written by hand and can,
// and the first draft of paper.md already quoted 2,375 bytes for fp12.sqr, a
// figure that had been 2,301 since the modulus stopped being pushed per module.
//
// So the load-bearing figures are listed here and checked to be present,
// formatted exactly as they should appear. This does not verify that the
// sentence around a number is true — nothing can — but it does mean the paper
// cannot silently claim a size the implementation no longer has.
//
// EACH ENTRY MUST BE DISTINCTIVE. The first version checked for the bare string
// "16" and passed while the paper said "15 of 15 reconstruct exactly", because
// some unrelated number contained "16". A two-digit substring is not evidence
// of anything. Short figures are therefore checked in the phrase they appear
// in, and anything below four digits needs one.
const G = r.pairing.onchain.grothVerifierInOneTransaction
// The chained pairing puts one stage in each TRANSACTION rather than each
// input, so its two stage sizes are in `parts` of the deployment row, and the
// row is the one the ledger reconstructs against the chain.
const CH = r.deployments.find((d) => /chainMiller/.test(d.name))
const PROSE = {
  'one pairing, bytes': n(r.pairing.e.bytes),
  'final exponentiation, bytes': n(r.pairing.finalExp.bytes),
  'Groth16 verifier, bytes': n(r.pairing.groth16.bytes),
  'Groth16 verifier, opcodes': n(r.pairing.groth16.opcodes),
  'script policy': n(r.scriptPolicyBytes),
  'saving on two pairings': n(r.pairing.products[1].saved),
  'saving on three pairings': n(r.pairing.products[2].saved),
  'the mainnet spend': r.pairing.onchain.wholePairingInOneTransaction.spend,
  'input 0 on chain': n(r.pairing.onchain.wholePairingInOneTransaction.publishBytes),
  'input 1 on chain': n(r.pairing.onchain.wholePairingInOneTransaction.consumeBytes),
  'final exponentiation as a share': pct(r.pairing.finalExp.bytes / r.pairing.e.bytes),
  'fp12.mul, marginal': n(M('fp12.mul').marginal),
  'fp12.sqr, marginal': n(M('fp12.sqr').marginal),
  'Miller loop witnesses': String(r.pairing.miller.witnesses),
  'deployments, in context': `${r.deployments.length} of ${r.deployments.length} reconstruct exactly`,
  'ladders, in context': `${r.pairing.finalExp.ladders} shared ladders`,
  'Miller loop, core': n(r.sizes.millerCore),
  'Miller loop, standalone': n(r.sizes.millerStandalone),
  'Miller loop, composed': n(r.sizes.millerComposed),
  'final exponentiation, standalone': n(r.sizes.finalExpStandalone),
  'final exponentiation, composed': n(r.sizes.finalExpComposed),
  // §8.3, the three-way split. G is the whole-verifier decomposition recorded
  // by tools/groth16-split.js.
  'three-pairing Miller loop': n(G.millerLoopThreePairs),
  'split stage 1, lock': n(G.lockBytes[0]),
  'split stage 2, lock': n(G.lockBytes[1]),
  'split stage 3, lock': n(G.lockBytes[2]),
  'split stage 3, unlock': n(G.unlockBytes[2]),
  'the blob': `${n(G.blobBytes)} bytes`,
  'the blob, in values': `${G.blobValues} field elements`,
  'the cut round, in context': `round ${G.cutRound} of 63`,
  'the split transaction': n(G.txBytes),
  'the triple grind': n(G.grindTries),
  'split stage 1, unlock': n(G.unlockBytes[0]),
  'split stage 1, subgroup checks': n(G.subgroupBytes[0]),
  // §8.4, one stage per transaction. Both figures are what the funding
  // transaction's outputs actually carry, checked byte for byte by
  // tools/verify-chainwalk.js.
  'chain tx₁, lock': n(CH.parts[0].lockBytes),
  'chain tx₂, lock': n(CH.parts[1].lockBytes),
  // §7.6, subgroup membership
  'subgroup checks in the verifier': n(r.pairing.groth16.subgroupCheckBytes),
  'the verifier without them': n(r.pairing.groth16.withoutSubgroupChecks),
  'g1.inSubgroup, standalone': n(M('g1.inSubgroup').bytes),
  'g2.inSubgroup, in context': `${M('g2.inSubgroup').bytes} bytes`
}

function checkProse () {
  const file = path.join(__dirname, '..', 'paper', 'paper.md')
  if (!fs.existsSync(file)) return []
  // Prose is wrapped, so a phrase can be split across a line break and a
  // literal includes() will miss it. Whitespace is collapsed on both sides
  // before comparing — otherwise the check fails for a reason that has nothing
  // to do with whether the number is right, which is worse than not checking.
  const flat = (s) => s.replace(/\s+/g, ' ')
  const text = flat(fs.readFileSync(file, 'utf8'))
  return Object.entries(PROSE).filter(([, value]) => !text.includes(flat(value)))
    .map(([what, value]) => `${what} (${value})`)
}

const check = process.argv.includes('--check')
const existing = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : ''
if (check) {
  if (existing !== doc) { console.log('paper: paper/tables.md is out of date — run `npm run paper`'); process.exit(1) }
  const missing = checkProse()
  if (missing.length) {
    console.log('paper: paper.md no longer quotes these measured figures —')
    for (const m of missing) console.log(`  ${m}`)
    process.exit(1)
  }
  console.log(`paper: tables.md matches results.json, and paper.md quotes all ${Object.keys(PROSE).length} load-bearing figures`)
} else {
  fs.writeFileSync(OUT, doc)
  const missing = checkProse()
  console.log(`paper: wrote paper/tables.md — 8 tables from results.json`)
  if (missing.length) {
    console.log('  paper.md does not quote:')
    for (const m of missing) console.log(`    ${m}`)
  }
}
