'use strict'

// Every txid in deployments.json, checked against the chain.
//
// A recorded transaction identifier is an assertion until someone asks a node
// about it. This asks: does the deployment exist, does its output carry exactly
// the locking script this repository builds today, does the spend reference it,
// and does the spend carry the unlocking script that was verified locally?
//
// The locking script is rebuilt from tools/targets.js and compared byte for
// byte, so this fails if the modules drift away from what was deployed — which
// is the point. A mainnet log that cannot be re-derived is a screenshot.
//
// It reads the RAW transaction and parses it here rather than trusting an API's
// decoded view. That is not pedantry: the decoded view truncates a large script
// at 50,000 characters, which made a 59,247-byte locking script look like a
// 50,000-byte one and reported a drift that had not happened.

const bsv = require('@smartledger/bsv')
const woc = require('../src/woc')
const onchain = require('../src/onchain')
const { targets, splitTargets } = require('./targets')

const fs = require('fs')
const path = require('path')

function writeLog (entries) {
  const rows = entries.map((e) => [
    `### ${e.target}`,
    '',
    e.claim,
    '',
    `| | |`,
    `| --- | --- |`,
    `| locking script | ${e.lockBytes.toLocaleString()} bytes |`,
    `| deploy | [\`${e.deploy}\`](https://whatsonchain.com/tx/${e.deploy}) |`,
    `| spend | [\`${e.spend}\`](https://whatsonchain.com/tx/${e.spend}) |`,
    ...(e.supersededBy ? [`| since corrected | ${e.supersededBy} |`] : []),
    ...(e.steps ? e.steps.map((st) => `| step ${st.from} → ${st.to} | [\`${st.txid}\`](https://whatsonchain.com/tx/${st.txid}) |`) : []),
    ''
  ].join('\n'))

  const doc = `# On chain

<!-- generated by tools/verify-chain.js — do not edit by hand -->

Everything else here is proven against \`bsv.Script.Interpreter\` — the evaluator
that validates blocks — which is a strong claim and not the same claim as *the
network accepted it*. Between the two sit relay policy, fee rates, and every
assumption a test harness makes about a transaction that a real one need not
share.

So each of these was deployed to an output on BSV mainnet and then **spent**. A
spend that the network accepted is the only evidence that leaves no room for the
harness to have been wrong: it means a node ran the locking script against the
unlocking script and agreed.

\`npm run verify:chain\` checks every identifier below against the chain — that
the deployment exists, that its output carries **exactly** the locking script
this repository builds today, that the spend consumes it, and that the spend
carries an unlocking script. It rebuilds the scripts from \`tools/targets.js\` and
compares byte for byte, so it fails if the modules drift from what was deployed.
A mainnet log that cannot be re-derived is a screenshot.

It reads raw transactions and parses them here rather than trusting a decoded
API view — which truncates a large script at 50,000 characters and made the
59,247-byte ECDSA locking script look like a 50,000-byte one that had drifted.

It asks two separate questions, because they have different meanings. **Is the
output byte for byte what was recorded?** That is a check, and it must hold.
**Does the code still build that script?** That is information: a module which
has since been corrected must build something else, and saying so is more honest
than a log that goes red or a log that quietly stops comparing. Where a
deployment has been superseded, the reason is printed with it.

${rows.join('\n')}
## What this does and does not show

It shows that these scripts are **relayable and spendable on mainnet today**: the
sizes, the flags, the fee rates and the policy rules are all real. It does not
show that any of the cryptography is sound — that is what the 183 cases and 537
forgery attempts are for, and no number of confirmations would add to it.
`
  fs.writeFileSync(path.join(__dirname, '..', 'docs', 'mainnet.md'), doc)
}

async function main () {
  const entries = onchain.ledger().deployments
  if (!entries.length) { console.log('nothing deployed yet'); return 0 }
  if (process.argv.includes('--write')) { writeLog(entries); console.log('docs/mainnet.md written') }

  let bad = 0
  for (const e of entries) {
    const target = targets[e.key] || (e.inputs ? splitTargets[e.key] : undefined)
    const rows = []
    let drift = null
    try {
      const depRaw = await woc.rawTx(e.deploy)
      const dep = new bsv.Transaction(depRaw)
      const onChainScript = dep.outputs[0].script.toHex()
      const depMeta = await woc.tx(e.deploy)
      rows.push(['deployment exists', true, `${(depRaw.length / 2).toLocaleString()} B, ${depMeta.confirmations || 0} conf`])
      // A deployment is usually ONE coin at output 0. The pairing split is two,
      // spent together, so its record carries an `inputs` list saying which
      // output holds which script and each is checked where it actually is.
      if (e.inputs) {
        for (const part of e.inputs) {
          const hex = dep.outputs[part.vout].script.toHex()
          rows.push([`output ${part.vout} is ${part.name}`, hex.length / 2 === part.lockBytes,
            `${hex.length / 2} B on chain, ${part.lockBytes} B recorded`])
        }
      } else {
        rows.push(['output 0 is the locking script', onChainScript.length / 2 === e.lockBytes, `${onChainScript.length / 2} B on chain, ${e.lockBytes} B recorded`])
      }
      // What was deployed must match what was recorded. That is a check.
      if (e.lockHex) {
        rows.push(['it is byte for byte what was recorded', e.lockHex === onChainScript, e.lockHex === onChainScript ? 'exactly' : 'THE RECORD IS WRONG'])
      }
      // Whether the CODE still builds it is a different question, and drift is
      // an answer rather than a failure: a module that has since been corrected
      // must build something else. It is reported, with the note saying why.
      if (target && target.parts && e.inputs) {
        // A deployment of several coins is rebuilt coin by coin, each compared
        // with the output it actually sits in.
        e.inputs.forEach((part, k) => {
          const rebuilt = target.parts[k].toHex()
          const same = rebuilt === dep.outputs[part.vout].script.toHex()
          drift = drift || (!same && { key: e.key, note: e.supersededBy })
          rows.push([same ? `the code still builds ${part.name}` : `the code has moved on from ${part.name}`, true,
            same ? 'byte for byte' : (e.supersededBy || 'reason not recorded')])
        })
      } else if (target) {
        const rebuilt = target.lock.toHex()
        const same = rebuilt === onChainScript
        drift = drift || (!same && { key: e.key, note: e.supersededBy })
        rows.push([same ? 'the code still builds it' : 'the code has moved on (see the note)', true,
          same ? 'byte for byte' : (e.supersededBy || 'reason not recorded')])
      }
      const spendRaw = await woc.rawTx(e.spend)
      const spend = new bsv.Transaction(spendRaw)
      const spendMeta = await woc.tx(e.spend)
      // A sequence's last spend consumes the step before it, not the deployment.
      const consumes = e.steps ? e.steps[e.steps.length - 2] && e.steps[e.steps.length - 2].txid : e.deploy
      if (e.inputs) {
        // Every coin has to be consumed, and by the SAME transaction — which is
        // the whole claim: two scripts bound to each other by one spend.
        for (const part of e.inputs) {
          const found = spend.inputs.some((v) => v.prevTxId.toString('hex') === e.deploy && v.outputIndex === part.vout)
          rows.push([`the spend consumes ${part.name}`, found, `input ${part.vout}`])
        }
        rows.push([`all ${e.inputs.length} in one transaction`, spend.inputs.length >= e.inputs.length,
          `${(spendRaw.length / 2).toLocaleString()} B, ${spendMeta.confirmations || 0} conf, ${spend.inputs.length} inputs`])
        rows.push(['it publishes the value they agree on', spend.outputs.length === 1 && spend.outputs[0].script.toBuffer()[1] === 0x6a,
          `${spend.outputs.length} output, OP_RETURN`])
      } else {
        const refs = spend.inputs.some((v) => v.prevTxId.toString('hex') === (consumes || e.deploy) && v.outputIndex === 0)
        rows.push(['the spend exists and consumes it', refs, `${(spendRaw.length / 2).toLocaleString()} B, ${spendMeta.confirmations || 0} conf`])
      }
      const unlockBytes = spend.inputs[0].script.toBuffer().length
      rows.push(['the unlocking script is present', unlockBytes > 0, `${unlockBytes.toLocaleString()} B`])
    } catch (err) {
      rows.push(['reachable', false, err.message.slice(0, 80)])
    }
    const ok = rows.every((r) => r[1])
    if (!ok) bad++
    console.log(`\n  ${ok ? 'ok  ' : 'FAIL'}  ${e.target}`)
    console.log(`        ${e.claim}`)
    for (const [what, good, detail] of rows) console.log(`        ${good ? '·' : '✗'} ${what.padEnd(44)} ${detail}`)
    console.log(`        deploy ${e.deploy}`)
    console.log(`        spend  ${e.spend}`)
  }
  console.log(`\n  ${entries.length - bad}/${entries.length} deployments verified against the chain\n`)
  return bad
}

main().then((bad) => process.exit(bad ? 1 : 0)).catch((e) => { console.error(e.message); process.exit(1) })
